/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:98352b13-33c1-4bcf-8c9d-87820a049ad8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ePEJUiOYC",
    "aws_user_pools_web_client_id": "r2a89d1dem0emtr7kqbvd1n9q",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://trko6fakhrechkff2hcsnizlzq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2eucphrwu5hz5kfgm7r5r2w4di",
    "aws_user_files_s3_bucket": "buckethaha154623-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
